# Generated by Django 3.2.9 on 2021-11-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('s', 'Sent'), ('f', 'Failed'), ('p', 'Pending')], default='pending', editable=False, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.ManyToManyField(to='sender.Recipient')),
            ],
            options={
                'verbose_name': 'E-mail Message',
                'verbose_name_plural': 'E-mail Messages',
            },
        ),
    ]
